// Elie Wiese-Namir © 2025. All Rights Reserved.

#pragma once

#include "Misc/Build.h"

#ifndef FLECS_LIBRARY_WITH_SOFT_ASSERT
#define FLECS_LIBRARY_WITH_SOFT_ASSERT 1
#endif // FLECS_LIBRARY_WITH_SOFT_ASSERT

#ifndef FLECS_LIBRARY_KEEP_ASSERT

#if DO_CHECK
#define FLECS_LIBRARY_KEEP_ASSERT 1
#else // DO_CHECK
#define FLECS_LIBRARY_KEEP_ASSERT 0
#endif // DO_CHECK

#endif // FLECS_LIBRARY_KEEP_ASSERT

#ifndef FLECS_LIBRARY_DISABLE_ALWAYS_INLINE
#define FLECS_LIBRARY_DISABLE_ALWAYS_INLINE 0
#endif // FLECS_LIBRARY_DISABLE_ALWAYS_INLINE

#ifndef FLECS_LIBRARY_WITH_LIBRARY_TESTS
#define FLECS_LIBRARY_WITH_LIBRARY_TESTS 0
#endif // FLECS_LIBRARY_WITH_LIBRARY_TESTS

#ifndef FLECS_LIBRARY_HI_COMPONENT_ID
#define FLECS_LIBRARY_HI_COMPONENT_ID 1024
#endif // FLECS_LIBRARY_HI_COMPONENT_ID

#ifndef FLECS_LIBRARY_HI_ID_RECORD_ID
#define FLECS_LIBRARY_HI_ID_RECORD_ID 1024
#endif // FLECS_LIBRARY_HI_ID_RECORD_ID

#ifndef FLECS_LIBRARY_SPARSE_PAGE_BITS
#define FLECS_LIBRARY_SPARSE_PAGE_BITS 6
#endif // FLECS_LIBRARY_SPARSE_PAGE_BITS

#ifndef FLECS_LIBRARY_ENTITY_PAGE_BITS
#define FLECS_LIBRARY_ENTITY_PAGE_BITS 10
#endif // FLECS_LIBRARY_ENTITY_PAGE_BITS

#ifndef FLECS_LIBRARY_DEFAULT_SYSTEM_PRIORITY
#define FLECS_LIBRARY_DEFAULT_SYSTEM_PRIORITY 100
#endif // FLECS_LIBRARY_DEFAULT_SYSTEM_PRIORITY

#ifndef FLECS_LIBRARY_WITH_JOURNAL
#define FLECS_LIBRARY_WITH_JOURNAL 0
#endif // FLECS_LIBRARY_WITH_JOURNAL

/** @def FLECS_EVENT_DESC_MAX
 * Maximum number of events in ecs_observer_desc_t. */
#ifndef FLECS_LIBRARY_EVENT_DESC_MAX
#define FLECS_LIBRARY_EVENT_DESC_MAX 8
#endif // FLECS_LIBRARY_EVENT_DESC_MAX

/** @def FLECS_ID_DESC_MAX
 * Maximum number of IDs to add in ecs_entity_desc_t / ecs_bulk_desc_t. */
#ifndef FLECS_LIBRARY_ID_DESC_MAX
#define FLECS_LIBRARY_ID_DESC_MAX 32
#endif // FLECS_LIBRARY_ID_DESC_MAX

/** @def FLECS_TERM_COUNT_MAX 
 * Maximum number of terms in queries. Should not exceed 64. */
#ifndef FLECS_LIBRARY_TERM_COUNT_MAX
#define FLECS_LIBRARY_TERM_COUNT_MAX 32
#endif // FLECS_LIBRARY_TERM_COUNT_MAX

/** @def FLECS_TERM_ARG_COUNT_MAX 
 * Maximum number of arguments for a term. */
#ifndef FLECS_LIBRARY_TERM_ARG_COUNT_MAX
#define FLECS_LIBRARY_TERM_ARG_COUNT_MAX 16 
#endif // FLECS_LIBRARY_TERM_ARG_COUNT_MAX

