// Elie Wiese-Namir © 2026. All Rights Reserved.

#include "Nodes/PinLogic/FlecsGenericInputPins.h"

#include "EdGraphSchema_K2.h"
#include "GameplayTagContainer.h"
#include "K2Node.h"

#include "Entities/FlecsId.h"
#include "Types/SolidEnumSelector.h"
#include "Types/SolidNotNull.h"

namespace UE::Flecs::GenericInputPins
{
	constexpr EFlecsBlueprintGenericPinTypes AllTypes[] = {
		EFlecsBlueprintGenericPinTypes::Id,
		EFlecsBlueprintGenericPinTypes::ScriptStruct,
		EFlecsBlueprintGenericPinTypes::Enum,
		EFlecsBlueprintGenericPinTypes::EnumConstant,
		EFlecsBlueprintGenericPinTypes::GameplayTag,
	};

} // namespace UE:

void FFlecsGenericInputPins::AllocatePins(
	const TSolidNotNull<UK2Node*> Node,
	const EFlecsBlueprintGenericPinTypes DefaultType) const
{
	const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema = GetDefault<UEdGraphSchema_K2>();
	const TSolidNotNull<UEnum*> GenericPinTypeEnum = StaticEnum<EFlecsBlueprintGenericPinTypes>();

	const TSolidNotNull<UEdGraphPin*> SelectorPin = Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Byte,
		GenericPinTypeEnum,
		GetSelectorPinName());

	const FString DefaultValue =
		GenericPinTypeEnum->GetNameStringByValue(static_cast<int64>(DefaultType));
	GraphSchema->SetPinAutogeneratedDefaultValue(SelectorPin, DefaultValue);
	GraphSchema->TrySetDefaultValue(*SelectorPin, DefaultValue);

	UEdGraphNode::FCreatePinParams PinParams;
	PinParams.bIsConst = true;

	Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Struct,
		TBaseStructure<FFlecsId>::Get(),
		GetValuePinName(EFlecsBlueprintGenericPinTypes::Id),
		PinParams);

	Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Object,
		UScriptStruct::StaticClass(),
		GetValuePinName(EFlecsBlueprintGenericPinTypes::ScriptStruct),
		PinParams);

	Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Object,
		UEnum::StaticClass(),
		GetValuePinName(EFlecsBlueprintGenericPinTypes::Enum),
		PinParams);

	Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Struct,
		TBaseStructure<FSolidEnumSelector>::Get(),
		GetValuePinName(EFlecsBlueprintGenericPinTypes::EnumConstant),
		PinParams);

	Node->CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Struct,
		TBaseStructure<FGameplayTag>::Get(),
		GetValuePinName(EFlecsBlueprintGenericPinTypes::GameplayTag),
		PinParams);

	RefreshPins(Node);
}

void FFlecsGenericInputPins::RefreshPins(const TSolidNotNull<UK2Node*> Node) const
{
	const TOptional<EFlecsBlueprintGenericPinTypes> SelectedType = GetSelectedType(Node);

	for (const EFlecsBlueprintGenericPinTypes Type : UE::Flecs::GenericInputPins::AllTypes)
	{
		if (UEdGraphPin* ValuePin = GetValuePin(Node, Type))
		{
			ValuePin->SafeSetHidden(!SelectedType.IsSet() || SelectedType.GetValue() != Type);
		}
	}
}

void FFlecsGenericInputPins::SetFriendlyNames(
	const TSolidNotNull<UK2Node*> Node,
	const FText& SelectorName,
	const FText& ValueName) const
{
	if (UEdGraphPin* SelectorPin = GetSelectorPin(Node))
	{
		SelectorPin->PinFriendlyName = SelectorName;
	}

	for (const EFlecsBlueprintGenericPinTypes Type : UE::Flecs::GenericInputPins::AllTypes)
	{
		if (UEdGraphPin* ValuePin = GetValuePin(Node, Type))
		{
			ValuePin->PinFriendlyName = ValueName;
		}
	}
}

void FFlecsGenericInputPins::SetPinsHidden(
	const TSolidNotNull<UK2Node*> Node,
	const bool bHidden) const
{
	if (UEdGraphPin* SelectorPin = GetSelectorPin(Node))
	{
		SelectorPin->SafeSetHidden(bHidden);
	}

	if (bHidden)
	{
		for (const EFlecsBlueprintGenericPinTypes Type : UE::Flecs::GenericInputPins::AllTypes)
		{
			if (UEdGraphPin* ValuePin = GetValuePin(Node, Type))
			{
				ValuePin->SafeSetHidden(true);
			}
		}
	}
	else
	{
		RefreshPins(Node);
	}
}

bool FFlecsGenericInputPins::IsSelectorPin(
	const TSolidNotNull<const UK2Node*> Node,
	const TSolidNotNull<const UEdGraphPin*> Pin) const
{
	return GetSelectorPin(Node) == Pin;
}

bool FFlecsGenericInputPins::IsManagedPin(
	const TSolidNotNull<const UK2Node*> Node,
	const TSolidNotNull<const UEdGraphPin*> Pin) const
{
	if (IsSelectorPin(Node, Pin))
	{
		return true;
	}

	for (const EFlecsBlueprintGenericPinTypes Type : UE::Flecs::GenericInputPins::AllTypes)
	{
		if (GetValuePin(Node, Type) == Pin)
		{
			return true;
		}
	}

	return false;
}

TOptional<EFlecsBlueprintGenericPinTypes> FFlecsGenericInputPins::GetSelectedType(const TSolidNotNull<const UK2Node*> Node) const
{
	const UEdGraphPin* SelectorPin = GetSelectorPin(Node);
	const UEnum* GenericPinTypeEnum = StaticEnum<EFlecsBlueprintGenericPinTypes>();

	if UNLIKELY_IF(!SelectorPin || !GenericPinTypeEnum)
	{
		return {};
	}

	const int64 Value = GenericPinTypeEnum->GetValueByNameString(SelectorPin->DefaultValue);

	if (Value == INDEX_NONE || !GenericPinTypeEnum->IsValidEnumValue(Value))
	{
		return {};
	}

	return static_cast<EFlecsBlueprintGenericPinTypes>(Value);
}

UEdGraphPin* FFlecsGenericInputPins::GetSelectorPin(const TSolidNotNull<const UK2Node*> Node) const
{
	return Node->FindPin(GetSelectorPinName(), EGPD_Input);
}

UEdGraphPin* FFlecsGenericInputPins::GetValuePin(const TSolidNotNull<const UK2Node*> Node,
	const EFlecsBlueprintGenericPinTypes Type) const
{
	return Node->FindPin(GetValuePinName(Type), EGPD_Input);
}

UEdGraphPin* FFlecsGenericInputPins::GetActiveValuePin(
	const TSolidNotNull<const UK2Node*> Node) const
{
	const TOptional<EFlecsBlueprintGenericPinTypes> SelectedType = GetSelectedType(Node);
	return SelectedType.IsSet() ? GetValuePin(Node, SelectedType.GetValue()) : nullptr;
}

FName FFlecsGenericInputPins::GetSelectorPinName() const
{
	return SelectorPinName.IsNone() ? MakePinName(TEXT("InputType")) : SelectorPinName;
}

FName FFlecsGenericInputPins::GetValuePinName(const EFlecsBlueprintGenericPinTypes Type) const
{
	switch (Type)
	{
	case EFlecsBlueprintGenericPinTypes::Id:
		return MakePinName(TEXT("Id"));
	case EFlecsBlueprintGenericPinTypes::ScriptStruct:
		return MakePinName(TEXT("ScriptStruct"));
	case EFlecsBlueprintGenericPinTypes::Enum:
		return MakePinName(TEXT("Enum"));
	case EFlecsBlueprintGenericPinTypes::EnumConstant:
		return MakePinName(TEXT("EnumConstant"));
	case EFlecsBlueprintGenericPinTypes::GameplayTag:
		return MakePinName(TEXT("GameplayTag"));
	default:
		return NAME_None;
	}
}

FName FFlecsGenericInputPins::MakePinName(const TCHAR* Suffix) const
{
	return Prefix.IsNone() ? FName(Suffix) : FName(Prefix.ToString() + Suffix);
}
