// Elie Wiese-Namir © 2026. All Rights Reserved.

#include "Nodes/K2Node_FlecsEntitySetOperation.h"

#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetCompiler.h"

#include "Libraries/FlecsEntityHandleFunctionLibrary.h"
#include "Types/SolidNotNull.h"

#include "Nodes/FlecsGenericNodeTypes.h"
#include "Nodes/PinLogic/FlecsEntityViewResolver.h"
#include "Nodes/PinLogic/FlecsGenericInputPins.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(K2Node_FlecsEntitySetOperation)

#define LOCTEXT_NAMESPACE "K2Node_FlecsEntitySetOperation"

namespace UE::Flecs::SetNode
{
	bool IsDataBearingType(const EFlecsBlueprintGenericPinTypes Type)
	{
		return Type == EFlecsBlueprintGenericPinTypes::Id ||
			Type == EFlecsBlueprintGenericPinTypes::ScriptStruct;
	}

	UK2Node_CallFunction* SpawnFunction(
		FKismetCompilerContext& CompilerContext,
		UK2Node* SourceNode,
		UEdGraph* SourceGraph,
		const FName FunctionName)
	{
		UK2Node_CallFunction* Function =
			CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(SourceNode, SourceGraph);
		Function->FunctionReference.SetExternalMember(
			FunctionName,
			UFlecsEntityHandleFunctionLibrary::StaticClass());
		Function->AllocateDefaultPins();
		return Function;
	}
} // namespace UE::Flecs::SetNode

void UK2Node_FlecsEntitySetOperation::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema = GetDefault<UEdGraphSchema_K2>();

	GetComponentPins().AllocatePins(this);
	GetComponentPins().SetFriendlyNames(
		this,
		LOCTEXT("ComponentTypePin", "Component Type"),
		LOCTEXT("ComponentPin", "Component"));

	UEdGraphPin* ValuePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, TEXT("Value"));
	ValuePin->PinFriendlyName = LOCTEXT("ValuePin", "Value");

	UEdGraphPin* SetPairPin = CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Boolean,
		TEXT("SetPair"));
	SetPairPin->PinFriendlyName = LOCTEXT("SetPairPin", "Set Pair");
	GraphSchema->SetPinAutogeneratedDefaultValue(SetPairPin, TEXT("false"));
	GraphSchema->TrySetDefaultValue(*SetPairPin, TEXT("false"));

	GetTargetPins().AllocatePins(this, EFlecsBlueprintGenericPinTypes::Id);
	GetTargetPins().SetFriendlyNames(
		this,
		LOCTEXT("TargetTypePin", "Target Type"),
		LOCTEXT("TargetPin", "Target"));

	RefreshPins();
}

void UK2Node_FlecsEntitySetOperation::ExpandNode(
	FKismetCompilerContext& CompilerContext,
	UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* ValuePin = GetValuePin();
	UScriptStruct* ValueScriptStruct = ValuePin
		? Cast<UScriptStruct>(ValuePin->PinType.PinSubCategoryObject.Get())
		: nullptr;
	const TOptional<EFlecsBlueprintGenericPinTypes> ComponentType =
		GetComponentPins().GetSelectedType(this);
	UEdGraphPin* ComponentValuePin = GetComponentPins().GetActiveValuePin(this);
	UScriptStruct* SelectedComponentScriptStruct =
		ComponentType.IsSet() &&
		ComponentType.GetValue() == EFlecsBlueprintGenericPinTypes::ScriptStruct
			? Cast<UScriptStruct>(ComponentValuePin
				? ComponentValuePin->DefaultObject
				: nullptr)
			: nullptr;
	const bool bSetPair = IsPairEnabled();
	const TOptional<EFlecsBlueprintGenericPinTypes> TargetType = bSetPair
		? GetTargetPins().GetSelectedType(this)
		: TOptional<EFlecsBlueprintGenericPinTypes>();
	if (!ValuePin || ValuePin->LinkedTo.Num() != 1 ||
		ValuePin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct ||
		!ValueScriptStruct ||
		!ComponentType.IsSet())
	{
		Message_Error(TEXT("Set requires one connected struct Value input and a valid component type."));
		BreakAllNodeLinks();
		return;
	}

	if (SelectedComponentScriptStruct &&
		SelectedComponentScriptStruct != ValueScriptStruct)
	{
		Message_Error(TEXT("Set component struct must match the Value input struct type."));
		BreakAllNodeLinks();
		return;
	}

	if (!bSetPair && !UE::Flecs::SetNode::IsDataBearingType(ComponentType.GetValue()))
	{
		Message_Error(TEXT("A non-pair Set component must be a Flecs id or script struct."));
		BreakAllNodeLinks();
		return;
	}

	if (bSetPair &&
		(!TargetType.IsSet() ||
			(!UE::Flecs::SetNode::IsDataBearingType(ComponentType.GetValue()) &&
				!UE::Flecs::SetNode::IsDataBearingType(TargetType.GetValue()))))
	{
		Message_Error(TEXT("Set Pair requires at least one Flecs id or script struct side."));
		BreakAllNodeLinks();
		return;
	}

	const TOptional<UE::Flecs::EntityViewResolver::FResolverSpec> ComponentResolverSpec =
		UE::Flecs::EntityViewResolver::GetResolverSpec(ComponentType.GetValue());
	if (!ComponentResolverSpec.IsSet() || ComponentResolverSpec.GetValue().bCompositePair)
	{
		Message_Error(TEXT("Set component must resolve to one Flecs id."));
		BreakAllNodeLinks();
		return;
	}

	if (!ComponentValuePin)
	{
		Message_Error(TEXT("Set requires a valid component input."));
		BreakAllNodeLinks();
		return;
	}

	const TSolidNotNull<UK2Node_CallFunction*> ComponentResolver =
		UE::Flecs::EntityViewResolver::SpawnResolver(
			CompilerContext,
			this,
			SourceGraph,
			ComponentResolverSpec.GetValue());
	CompilerContext.CopyPinLinksToIntermediate(
		*GetEntityPin(),
		*ComponentResolver->FindPinChecked(TEXT("Entity")));

	if (ComponentType.GetValue() == EFlecsBlueprintGenericPinTypes::ScriptStruct)
	{
		UEdGraphPin* ScriptStructPin =
			ComponentResolver->FindPinChecked(ComponentResolverSpec.GetValue().ValueParameterName);
		if (ComponentValuePin->LinkedTo.IsEmpty() && !ComponentValuePin->DefaultObject)
		{
			ScriptStructPin->DefaultObject = ValueScriptStruct;
		}
		else
		{
			CompilerContext.MovePinLinksToIntermediate(
				*ComponentValuePin,
				*ScriptStructPin);
		}
	}
	else
	{
		CompilerContext.MovePinLinksToIntermediate(
			*ComponentValuePin,
			*ComponentResolver->FindPinChecked(ComponentResolverSpec.GetValue().ValueParameterName));
	}

	UEdGraphPin* FinalComponentIdPin =
		ComponentResolver->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue);

	if (bSetPair)
	{
		UEdGraphPin* TargetValuePin = GetTargetPins().GetActiveValuePin(this);
		if (!TargetType.IsSet() || !TargetValuePin)
		{
			Message_Error(TEXT("Set Pair requires a valid target input."));
			BreakAllNodeLinks();
			return;
		}

		const TOptional<UE::Flecs::EntityViewResolver::FResolverSpec> TargetResolverSpec =
			UE::Flecs::EntityViewResolver::GetResolverSpec(TargetType.GetValue());
		if (!TargetResolverSpec.IsSet() || TargetResolverSpec.GetValue().bCompositePair)
		{
			Message_Error(TEXT("Set Pair target must resolve to one Flecs id."));
			BreakAllNodeLinks();
			return;
		}

		const TSolidNotNull<UK2Node_CallFunction*> TargetResolver =
			UE::Flecs::EntityViewResolver::SpawnResolver(
				CompilerContext,
				this,
				SourceGraph,
				TargetResolverSpec.GetValue());
		CompilerContext.CopyPinLinksToIntermediate(
			*GetEntityPin(),
			*TargetResolver->FindPinChecked(TEXT("Entity")));
		CompilerContext.MovePinLinksToIntermediate(
			*TargetValuePin,
			*TargetResolver->FindPinChecked(TargetResolverSpec.GetValue().ValueParameterName));

		const TSolidNotNull<UK2Node_CallFunction*> MakePairFunction =
			UE::Flecs::SetNode::SpawnFunction(
				CompilerContext,
				this,
				SourceGraph,
				GET_FUNCTION_NAME_CHECKED(
					UFlecsEntityHandleFunctionLibrary,
					EntityHandle_MakePairId));

		const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema = GetDefault<UEdGraphSchema_K2>();
		const bool bConnectedRelation = GraphSchema->TryCreateConnection(
			FinalComponentIdPin,
			MakePairFunction->FindPinChecked(TEXT("RelationId")));
		const bool bConnectedTarget = GraphSchema->TryCreateConnection(
			TargetResolver->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue),
			MakePairFunction->FindPinChecked(TEXT("TargetId")));
		if (!bConnectedRelation || !bConnectedTarget)
		{
			Message_Error(TEXT("Failed to create the Set Pair id."));
			BreakAllNodeLinks();
			return;
		}

		FinalComponentIdPin =
			MakePairFunction->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue);
	}

	const TSolidNotNull<UK2Node_CallFunction*> SetFunction =
		UE::Flecs::SetNode::SpawnFunction(
			CompilerContext,
			this,
			SourceGraph,
			GET_FUNCTION_NAME_CHECKED(
				UFlecsEntityHandleFunctionLibrary,
				EntityHandle_SetId));

	UEdGraphPin* SetValuePin = SetFunction->FindPinChecked(TEXT("Value"));
	SetValuePin->PinType = ValuePin->PinType;

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *SetFunction->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*GetThenPin(), *SetFunction->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(
		*GetEntityPin(),
		*SetFunction->FindPinChecked(TEXT("Entity")));
	CompilerContext.MovePinLinksToIntermediate(*ValuePin, *SetValuePin);

	const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema = GetDefault<UEdGraphSchema_K2>();
	if (!GraphSchema->TryCreateConnection(
		FinalComponentIdPin,
		SetFunction->FindPinChecked(TEXT("ComponentId"))))
	{
		Message_Error(TEXT("Failed to connect the resolved Flecs id to the Set operation."));
	}

	BreakAllNodeLinks();
}

FText UK2Node_FlecsEntitySetOperation::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return LOCTEXT("NodeTitle", "Set Component on Flecs Entity");
}

bool UK2Node_FlecsEntitySetOperation::IsConnectionDisallowed(
	const UEdGraphPin* MyPin,
	const UEdGraphPin* OtherPin,
	FString& OutReason) const
{
	if (MyPin == GetValuePin() && OtherPin->PinType.PinCategory != UEdGraphSchema_K2::PC_Struct)
	{
		OutReason = LOCTEXT("ValueMustBeStruct", "Set Value must be a struct.").ToString();
		return true;
	}

	return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
}

void UK2Node_FlecsEntitySetOperation::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);

	if (Pin == GetValuePin())
	{
		SynchronizeValuePinType();
	}
}

void UK2Node_FlecsEntitySetOperation::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	const bool bComponentScriptStructChanged =
		Pin &&
		GetComponentPins().GetValuePin(
			this,
			EFlecsBlueprintGenericPinTypes::ScriptStruct) == Pin;

	if (Pin == GetSetPairPin() ||
		(Pin && (GetComponentPins().IsSelectorPin(this, Pin) ||
			GetTargetPins().IsSelectorPin(this, Pin))) ||
		bComponentScriptStructChanged)
	{
		RefreshPins();

		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyGraphChanged();
		}
	}
}

void UK2Node_FlecsEntitySetOperation::PinTypeChanged(UEdGraphPin* Pin)
{
	Super::PinTypeChanged(Pin);

	if (Pin == GetValuePin())
	{
		SynchronizeValuePinType();
	}
}

void UK2Node_FlecsEntitySetOperation::PostReconstructNode()
{
	Super::PostReconstructNode();
	SynchronizeValuePinType();
	RefreshPins();
}

const FFlecsGenericInputPins& UK2Node_FlecsEntitySetOperation::GetComponentPins()
{
	static const FFlecsGenericInputPins ComponentPins(
		TEXT("Component"),
		TEXT("ComponentType"));
	return ComponentPins;
}

const FFlecsGenericInputPins& UK2Node_FlecsEntitySetOperation::GetTargetPins()
{
	static const FFlecsGenericInputPins TargetPins(TEXT("Target"));
	return TargetPins;
}

UEdGraphPin* UK2Node_FlecsEntitySetOperation::GetValuePin() const
{
	return FindPin(TEXT("Value"), EGPD_Input);
}

UEdGraphPin* UK2Node_FlecsEntitySetOperation::GetSetPairPin() const
{
	return FindPin(TEXT("SetPair"), EGPD_Input);
}

bool UK2Node_FlecsEntitySetOperation::IsPairEnabled() const
{
	const UEdGraphPin* SetPairPin = GetSetPairPin();
	return SetPairPin && SetPairPin->DefaultValue.ToBool();
}

void UK2Node_FlecsEntitySetOperation::RefreshPins()
{
	const bool bSetPair = IsPairEnabled();
	if (UEdGraphPin* ComponentTypePin = GetComponentPins().GetSelectorPin(this))
	{
		ComponentTypePin->PinType.PinSubCategoryObject = bSetPair ? StaticEnum<EFlecsBlueprintGenericPinTypes>()
			: StaticEnum<EFlecsBlueprintSetComponentType>();

		const TOptional<EFlecsBlueprintGenericPinTypes> ComponentType = GetComponentPins().GetSelectedType(this);
		if (!bSetPair && (!ComponentType.IsSet() ||
				!UE::Flecs::SetNode::IsDataBearingType(ComponentType.GetValue())))
		{
			GetDefault<UEdGraphSchema_K2>()->TrySetDefaultValue(
				*ComponentTypePin,
				TEXT("ScriptStruct"));
		}
	}

	GetComponentPins().SetPinsHidden(this, false);

	GetTargetPins().SetPinsHidden(this, !bSetPair);
}

void UK2Node_FlecsEntitySetOperation::SynchronizeValuePinType()
{
	UEdGraphPin* ValuePin = GetValuePin();
	
	if (!ValuePin)
	{
		return;
	}

	FEdGraphPinType NewPinType;
	NewPinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
	if (ValuePin->LinkedTo.Num() == 1)
	{
		NewPinType = ValuePin->LinkedTo[0]->PinType;
	}

	if (ValuePin->PinType != NewPinType)
	{
		ValuePin->PinType = NewPinType;

		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}

		UBlueprint* Blueprint = GetBlueprint(); 
		
		if (Blueprint && !Blueprint->bBeingCompiled)
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		}
	}
}

#undef LOCTEXT_NAMESPACE
