// Elie Wiese-Namir © 2026. All Rights Reserved.

#include "Nodes/K2Node_FlecsEntityModifiedOperation.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"

#include "Libraries/FlecsEntityHandleFunctionLibrary.h"
#include "Types/SolidNotNull.h"

#include "Nodes/FlecsGenericNodeTypes.h"
#include "Nodes/PinLogic/FlecsEntityViewResolver.h"
#include "Nodes/PinLogic/FlecsGenericInputPins.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(K2Node_FlecsEntityModifiedOperation)

namespace UE::Flecs::ModifiedNode
{
	bool IsDataBearingType(const EFlecsBlueprintGenericPinTypes Type)
	{
		return Type == EFlecsBlueprintGenericPinTypes::Id ||
			Type == EFlecsBlueprintGenericPinTypes::ScriptStruct;
	}

	struct FOperationSpec
	{
		FName FunctionName;
		FName ValueParameterName;
	};

	TOptional<FOperationSpec> GetOperationSpec(const EFlecsBlueprintGenericPinTypes Type)
	{
		switch (Type)
		{
		case EFlecsBlueprintGenericPinTypes::Id:
			return FOperationSpec{
				GET_FUNCTION_NAME_CHECKED(
					UFlecsEntityHandleFunctionLibrary,
					EntityHandle_ModifiedId),
				TEXT("ComponentId")
			};
		case EFlecsBlueprintGenericPinTypes::ScriptStruct:
			return FOperationSpec{
				GET_FUNCTION_NAME_CHECKED(
					UFlecsEntityHandleFunctionLibrary,
					EntityHandle_ModifiedScriptStruct),
				TEXT("ScriptStruct")
			};
		default:
			return {};
		}
	}
} // namespace UE::Flecs::ModifiedNode

void UK2Node_FlecsEntityModifiedOperation::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();

	const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema = GetDefault<UEdGraphSchema_K2>();

	GetComponentPins().AllocatePins(this);
	GetComponentPins().SetFriendlyNames(
		this,
		FText::FromString(TEXT("Component Type")),
		FText::FromString(TEXT("Component")));

	UEdGraphPin* ModifiedPairPin = CreatePin(
		EGPD_Input,
		UEdGraphSchema_K2::PC_Boolean,
		TEXT("ModifiedPair"));
	ModifiedPairPin->PinFriendlyName = FText::FromString(TEXT("Modified Pair"));
	GraphSchema->SetPinAutogeneratedDefaultValue(ModifiedPairPin, TEXT("false"));
	GraphSchema->TrySetDefaultValue(*ModifiedPairPin, TEXT("false"));

	GetTargetPins().AllocatePins(this, EFlecsBlueprintGenericPinTypes::Id);
	GetTargetPins().SetFriendlyNames(
		this,
		FText::FromString(TEXT("Target Type")),
		FText::FromString(TEXT("Target")));

	RefreshPins();
}

void UK2Node_FlecsEntityModifiedOperation::ExpandNode(
	FKismetCompilerContext& CompilerContext,
	UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const TOptional<EFlecsBlueprintGenericPinTypes> SelectedType =
		GetComponentPins().GetSelectedType(this);
	UEdGraphPin* ActiveValuePin = GetComponentPins().GetActiveValuePin(this);
	const bool bModifiedPair = IsPairEnabled();
	const TOptional<EFlecsBlueprintGenericPinTypes> TargetType = bModifiedPair
		? GetTargetPins().GetSelectedType(this)
		: TOptional<EFlecsBlueprintGenericPinTypes>();

	if (!SelectedType.IsSet() || !ActiveValuePin)
	{
		Message_Error(TEXT("Modified requires a valid component input."));
		BreakAllNodeLinks();
		return;
	}

	if (bModifiedPair)
	{
		UEdGraphPin* TargetValuePin = GetTargetPins().GetActiveValuePin(this);
		if (!TargetType.IsSet() || !TargetValuePin ||
			(!UE::Flecs::ModifiedNode::IsDataBearingType(SelectedType.GetValue()) &&
				!UE::Flecs::ModifiedNode::IsDataBearingType(TargetType.GetValue())))
		{
			Message_Error(TEXT("Modified Pair requires a target and at least one Flecs id or script struct side."));
			BreakAllNodeLinks();
			return;
		}

		const TOptional<UE::Flecs::EntityViewResolver::FResolverSpec> RelationResolverSpec =
			UE::Flecs::EntityViewResolver::GetResolverSpec(SelectedType.GetValue());
		const TOptional<UE::Flecs::EntityViewResolver::FResolverSpec> TargetResolverSpec =
			UE::Flecs::EntityViewResolver::GetResolverSpec(TargetType.GetValue());
		if (!RelationResolverSpec.IsSet() || RelationResolverSpec.GetValue().bCompositePair ||
			!TargetResolverSpec.IsSet() || TargetResolverSpec.GetValue().bCompositePair)
		{
			Message_Error(TEXT("Modified Pair inputs must each resolve to one Flecs id."));
			BreakAllNodeLinks();
			return;
		}

		const TSolidNotNull<UK2Node_CallFunction*> RelationResolver =
			UE::Flecs::EntityViewResolver::SpawnResolver(
				CompilerContext,
				this,
				SourceGraph,
				RelationResolverSpec.GetValue());
		const TSolidNotNull<UK2Node_CallFunction*> TargetResolver =
			UE::Flecs::EntityViewResolver::SpawnResolver(
				CompilerContext,
				this,
				SourceGraph,
				TargetResolverSpec.GetValue());
		const TSolidNotNull<UK2Node_CallFunction*> ModifiedPairFunction =
			CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		ModifiedPairFunction->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(
				UFlecsEntityHandleFunctionLibrary,
				EntityHandle_ModifiedPairIds),
			UFlecsEntityHandleFunctionLibrary::StaticClass());
		ModifiedPairFunction->AllocateDefaultPins();

		CompilerContext.MovePinLinksToIntermediate(
			*GetExecPin(),
			*ModifiedPairFunction->GetExecPin());
		CompilerContext.MovePinLinksToIntermediate(
			*GetThenPin(),
			*ModifiedPairFunction->GetThenPin());
		CompilerContext.CopyPinLinksToIntermediate(
			*GetEntityPin(),
			*RelationResolver->FindPinChecked(TEXT("Entity")));
		CompilerContext.CopyPinLinksToIntermediate(
			*GetEntityPin(),
			*TargetResolver->FindPinChecked(TEXT("Entity")));
		CompilerContext.MovePinLinksToIntermediate(
			*GetEntityPin(),
			*ModifiedPairFunction->FindPinChecked(TEXT("Entity")));
		CompilerContext.MovePinLinksToIntermediate(
			*ActiveValuePin,
			*RelationResolver->FindPinChecked(
				RelationResolverSpec.GetValue().ValueParameterName));
		CompilerContext.MovePinLinksToIntermediate(
			*TargetValuePin,
			*TargetResolver->FindPinChecked(
				TargetResolverSpec.GetValue().ValueParameterName));

		const TSolidNotNull<const UEdGraphSchema_K2*> GraphSchema =
			GetDefault<UEdGraphSchema_K2>();
		const bool bConnectedRelation = GraphSchema->TryCreateConnection(
			RelationResolver->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue),
			ModifiedPairFunction->FindPinChecked(TEXT("RelationId")));
		const bool bConnectedTarget = GraphSchema->TryCreateConnection(
			TargetResolver->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue),
			ModifiedPairFunction->FindPinChecked(TEXT("TargetId")));
		if (!bConnectedRelation || !bConnectedTarget)
		{
			Message_Error(TEXT("Failed to connect the resolved Flecs ids to Modified Pair."));
		}

		BreakAllNodeLinks();
		return;
	}

	const TOptional<UE::Flecs::ModifiedNode::FOperationSpec> OperationSpec =
		UE::Flecs::ModifiedNode::GetOperationSpec(SelectedType.GetValue());
	if (!OperationSpec.IsSet())
	{
		Message_Error(TEXT("Modified requires a Flecs id or script struct component."));
		BreakAllNodeLinks();
		return;
	}

	const TSolidNotNull<UK2Node_CallFunction*> ModifiedFunction =
		CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	ModifiedFunction->FunctionReference.SetExternalMember(
		OperationSpec.GetValue().FunctionName,
		UFlecsEntityHandleFunctionLibrary::StaticClass());
	ModifiedFunction->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *ModifiedFunction->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*GetThenPin(), *ModifiedFunction->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(
		*GetEntityPin(),
		*ModifiedFunction->FindPinChecked(TEXT("Entity")));
	CompilerContext.MovePinLinksToIntermediate(
		*ActiveValuePin,
		*ModifiedFunction->FindPinChecked(OperationSpec.GetValue().ValueParameterName));

	BreakAllNodeLinks();
}

FText UK2Node_FlecsEntityModifiedOperation::GetNodeTitle(
	ENodeTitleType::Type TitleType) const
{
	return FText::FromString(TEXT("Mark Flecs Component Modified"));
}

void UK2Node_FlecsEntityModifiedOperation::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin == GetModifiedPairPin() ||
		(Pin && (GetComponentPins().IsSelectorPin(this, Pin) ||
			GetTargetPins().IsSelectorPin(this, Pin))))
	{
		RefreshPins();

		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyGraphChanged();
		}
	}
}

void UK2Node_FlecsEntityModifiedOperation::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshPins();
}

const FFlecsGenericInputPins& UK2Node_FlecsEntityModifiedOperation::GetComponentPins()
{
	static const FFlecsGenericInputPins ComponentPins(
		TEXT("Component"),
		TEXT("ComponentType"));
	return ComponentPins;
}

const FFlecsGenericInputPins& UK2Node_FlecsEntityModifiedOperation::GetTargetPins()
{
	static const FFlecsGenericInputPins TargetPins(TEXT("Target"));
	return TargetPins;
}

UEdGraphPin* UK2Node_FlecsEntityModifiedOperation::GetModifiedPairPin() const
{
	return FindPin(TEXT("ModifiedPair"), EGPD_Input);
}

bool UK2Node_FlecsEntityModifiedOperation::IsPairEnabled() const
{
	const UEdGraphPin* ModifiedPairPin = GetModifiedPairPin();
	return ModifiedPairPin && ModifiedPairPin->DefaultValue.ToBool();
}

void UK2Node_FlecsEntityModifiedOperation::RefreshPins()
{
	const bool bModifiedPair = IsPairEnabled();
	if (UEdGraphPin* ComponentTypePin = GetComponentPins().GetSelectorPin(this))
	{
		ComponentTypePin->PinType.PinSubCategoryObject = bModifiedPair
			? StaticEnum<EFlecsBlueprintGenericPinTypes>()
			: StaticEnum<EFlecsBlueprintSetComponentType>();

		const TOptional<EFlecsBlueprintGenericPinTypes> ComponentType =
			GetComponentPins().GetSelectedType(this);
		if (!bModifiedPair &&
			(!ComponentType.IsSet() ||
				!UE::Flecs::ModifiedNode::IsDataBearingType(ComponentType.GetValue())))
		{
			GetDefault<UEdGraphSchema_K2>()->TrySetDefaultValue(
				*ComponentTypePin,
				TEXT("ScriptStruct"));
		}
	}

	GetComponentPins().SetPinsHidden(this, false);
	GetTargetPins().SetPinsHidden(this, !bModifiedPair);
}
